import type { Breach } from "@/data/breaches"
import type { DataBroker } from "@/data/brokers"

export const PROFILE_KEY = "traceless_profile"

export interface UserProfile {
  name: string
  address?: string
  dni?: string
  phone?: string
  email?: string
}

export function generateDeletionLetter(query: string, breach: Breach, profile?: UserProfile): string {
  const date = new Date().toLocaleDateString("es-AR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const fullName = profile?.name || "[TU NOMBRE COMPLETO]"
  const addressLine = profile?.address || "[Dirección (opcional)]"
  const dniLine = profile?.dni || "[DNI/Pasaporte (opcional)]"

  return `Asunto: Data Deletion Request - Right to Erasure / Derecho al Olvido

${date}

To: Privacy Department / Data Protection Officer
${breach.name}
${breach.domain}

Dear Sir or Madam,

I am writing to request the complete deletion of my personal data associated with the email address ${query}, in accordance with the following regulations:

1. **GDPR (General Data Protection Regulation)** - Article 17: Right to Erasure
   (Applicable in the European Union and for companies operating in/with EU citizens)

2. **CCPA (California Consumer Privacy Act)** - Section 1798.105: Right to Delete
   (Applicable for California residents and companies doing business in California)

3. **Ley 25.326 - Protección de Datos Personales** (Argentina)
   (Applicable for Argentine citizens and companies processing Argentine data)

4. **Additional local data protection laws** as applicable in your jurisdiction.

**Context of this request:**

My personal data was exposed in a security breach at ${breach.name} on ${breach.date || "an unknown date"}. The compromised data includes: ${breach.compromisedData.join(", ")}.

**I hereby request:**

1. Complete deletion of all personal data associated with ${query} from your systems and databases.
2. Written confirmation that such deletion has been carried out.
3. Notification to any third parties who received my data about this deletion request.
4. Information about the timeframe for complete deletion (maximum 30 days as per GDPR).

This request is made in exercise of my fundamental right to data protection and privacy.

I expect a response within 30 days as required by applicable data protection regulations.

Sincerely,

${fullName}
Email: ${query}
${addressLine}
${dniLine}

---
This message was generated by TraceLess - Privacy Protection Tool`
}

export function generateDeletionLetterHTML(query: string, breach: Breach, date: string, profile?: UserProfile): string {
  const d = new Date(date)
  const dateStr = d.toLocaleDateString("es-AR", { day: "numeric", month: "long", year: "numeric" })
  const fullName = profile?.name || "[TU NOMBRE COMPLETO]"
  const addressLine = profile?.address ? `<br />${profile.address}` : ""
  const dniLine = profile?.dni ? `<br />${profile.dni}` : ""

  return `<div style="font-family: 'Georgia', serif; max-width: 700px; margin: 0 auto; padding: 60px 40px; color: #111;">
    <p style="text-align: right; color: #666; font-size: 14px; margin-bottom: 40px;">${dateStr}</p>

    <p style="margin-bottom: 30px;">
      <strong>${breach.name}</strong><br />
      Att: Privacy Department / Data Protection Officer<br />
      ${breach.domain}
    </p>

    <p style="margin-bottom: 20px;"><strong>Ref: Data Deletion Request - Right to Erasure</strong></p>

    <p style="margin-bottom: 15px;">Dear Sir or Madam,</p>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      I am writing to request the <strong>complete deletion</strong> of all my personal data
      associated with the email address <strong>${query}</strong>,
      in accordance with the following data protection regulations:
    </p>

    <ul style="margin-bottom: 20px; line-height: 1.8; padding-left: 20px;">
      <li><strong>GDPR</strong> (General Data Protection Regulation) - Article 17: Right to Erasure</li>
      <li><strong>CCPA</strong> (California Consumer Privacy Act) - Section 1798.105: Right to Delete</li>
      <li><strong>Ley 25.326</strong> - Protección de Datos Personales (Argentina)</li>
      <li>Any other applicable local data protection legislation</li>
    </ul>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      My personal data was exposed in a security breach at
      <strong>${breach.name}</strong> on <strong>${breach.date}</strong>.
      The compromised data includes: <strong>${breach.compromisedData.join(", ")}</strong>.
    </p>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      In accordance with the above regulations, I request that:
    </p>

    <ol style="margin-bottom: 20px; line-height: 1.8;">
      <li>All my personal data be deleted from your systems and databases.</li>
      <li>Any processing of my data be discontinued.</li>
      <li>Third parties who received my data be notified of this deletion request.</li>
      <li>Written confirmation of deletion be provided within 30 days.</li>
    </ol>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      I expect a response within 30 days as required by applicable data protection regulations.
    </p>

    <p style="margin-bottom: 40px; line-height: 1.6;">
      I look forward to your prompt response.
    </p>

    <p style="margin-bottom: 5px;">Sincerely,</p>
    <p>
      <strong>${fullName}</strong><br />
      ${query}${addressLine}${dniLine}
    </p>

    <p style="margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px;">
      This message was generated by TraceLess - Privacy Protection Tool
    </p>
  </div>`
}

export function generateMasterDeletionLetter(emails: string[], profile?: UserProfile): string {
  const date = new Date().toLocaleDateString("es-AR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const fullName = profile?.name || "[TU NOMBRE COMPLETO]"
  const contactEmail = emails[0] || "[Correo de contacto]"
  const addressLine = profile?.address ? `\n${profile.address}` : "\n[Dirección (opcional)]"

  const emailList = emails.map((e) => `  - ${e}`).join("\n")

  return `Asunto: Data Deletion Request - Right to Erasure / Derecho al Olvido

${date}

To: Privacy Department / Data Protection Officer

Dear Sir or Madam,

I am writing to request the complete deletion of my personal data associated with the following email addresses:

${emailList}

This request is made in accordance with:

1. **GDPR** (General Data Protection Regulation) - Article 17: Right to Erasure
2. **CCPA** (California Consumer Privacy Act) - Section 1798.105: Right to Delete
3. **Ley 25.326** - Protección de Datos Personales (Argentina)
4. Any other applicable local data protection legislation

I request:
1. Complete deletion of all my personal data from your systems.
2. Written confirmation of deletion within 30 days.
3. Notification to third parties who received my data about this request.

Sincerely,

${fullName}
Email: ${contactEmail}${addressLine}

---
This message was generated by TraceLess - Privacy Protection Tool`
}

export function generateHabeasDataLetter(broker: DataBroker, profile: UserProfile): string {
  const date = new Date().toLocaleDateString("es-AR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const fullName = profile.name || "[TU NOMBRE COMPLETO]"
  const dni = profile.dni || "[TU DNI]"
  const address = profile.address || "[TU DOMICILIO COMPLETO]"
  const phone = profile.phone || "[TU TELÉFONO]"
  const email = profile.email || "[TU EMAIL]"

  return `Asunto: Solicitud de eliminación de datos personales - Ley 25.326 (Habeas Data)

${date}

A la atención de:
${broker.name}
${broker.domain}
[Departamento de Privacidad / Oficial de Protección de Datos]

Por medio de la presente, solicito formalmente la eliminación de todos mis datos personales que se encuentran registrados en su base de datos, de conformidad con lo establecido en:

**Ley N° 25.326 - Protección de Datos Personales y Habeas Data**

Específicamente:

- **Artículo 16**: Derecho de supresión. El titular de los datos personales tiene derecho a solicitar en cualquier momento la supresión total o parcial de los mismos cuando se consideren innecesarios o excesivos para la finalidad para la que han sido recolectados.

- **Artículo 26**: Obligación de notificación. Los organismos públicos y las entidades privadas que realicen o no tareas de tratamiento de datos personales están obligados a registrar y notificar a la autoridad de aplicación las violaciones de la seguridad de los datos de carácter personal.

Mis datos personales que deben ser eliminados son:

- Nombre y apellido: ${fullName}
- DNI: ${dni}
- Domicilio: ${address}
- Teléfono: ${phone}
- Email: ${email}
- CUIL/CUIT: ${profile.dni ? `[Si aplica]` : "[No proporcionado]"}

**Solicito:**

1. Eliminación completa e inmediata de todos mis datos personales de sus sistemas, bases de datos y registros.
2. Confirmación escrita de la eliminación realizada dentro de los 10 días hábiles siguientes a la recepción de esta solicitud.
3. Notificación a cualquier tercero que haya recibido mis datos sobre esta solicitud de eliminación.
4. Cesación de cualquier tratamiento futuro de mis datos personales.

**Fundamento legal adicional:**

- Artículo 43 de la Constitución Nacional Argentina: Derecho al Habeas Data
- Decreto 1558/2001: Reglamentario de la Ley 25.326
- Resoluciones de la Agencia de Acceso a la Información Pública

En caso de no recibir respuesta satisfactoria dentro del plazo legal, me reservo el derecho de realizar la correspondiente denuncia ante la Agencia de Acceso a la Información Pública y/o iniciar las acciones legales pertinentes.

Sin otro particular, saludo atentamente,

${fullName}
DNI: ${dni}
Domicilio: ${address}
Teléfono: ${phone}
Email: ${email}

---
Este documento fue generado por TraceLess - Herramienta de Protección de Privacidad
Fundamento legal: Ley 25.326 - Protección de Datos Personales (Argentina)`
}

export function generateHabeasDataLetterHTML(broker: DataBroker, profile: UserProfile, date: string): string {
  const d = new Date(date)
  const dateStr = d.toLocaleDateString("es-AR", { day: "numeric", month: "long", year: "numeric" })
  const fullName = profile.name || "[TU NOMBRE COMPLETO]"
  const dni = profile.dni || "[TU DNI]"
  const address = profile.address || "[TU DOMICILIO COMPLETO]"
  const phone = profile.phone || "[TU TELÉFONO]"
  const email = profile.email || "[TU EMAIL]"

  return `<div style="font-family: 'Georgia', serif; max-width: 700px; margin: 0 auto; padding: 60px 40px; color: #111;">
    <p style="text-align: right; color: #666; font-size: 14px; margin-bottom: 40px;">${dateStr}</p>

    <p style="margin-bottom: 30px;">
      <strong>${broker.name}</strong><br />
      Att: Departamento de Privacidad / Oficial de Protección de Datos<br />
      ${broker.domain}
    </p>

    <p style="margin-bottom: 20px;"><strong>Ref: Solicitud de eliminación de datos personales - Ley 25.326 (Habeas Data)</strong></p>

    <p style="margin-bottom: 15px;">Por medio de la presente, solicito formalmente la eliminación de todos mis datos personales que se encuentran registrados en su base de datos, de conformidad con lo establecido en:</p>

    <p style="margin-bottom: 15px; line-height: 1.6;"><strong>Ley N° 25.326 - Protección de Datos Personales y Habeas Data</strong></p>

    <ul style="margin-bottom: 20px; line-height: 1.8; padding-left: 20px;">
      <li><strong>Artículo 16</strong>: Derecho de supresión. El titular tiene derecho a solicitar la supresión total o parcial de datos innecesarios o excesivos.</li>
      <li><strong>Artículo 26</strong>: Obligación de notificación sobre violaciones de seguridad.</li>
      <li><strong>Artículo 43 CN</strong>: Derecho al Habeas Data.</li>
    </ul>

    <p style="margin-bottom: 15px; line-height: 1.6;"><strong>Datos personales a eliminar:</strong></p>

    <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px;">
      <tr><td style="padding: 8px; border-bottom: 1px solid #eee; width: 40%;"><strong>Nombre y apellido</strong></td><td style="padding: 8px; border-bottom: 1px solid #eee;">${fullName}</td></tr>
      <tr><td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>DNI</strong></td><td style="padding: 8px; border-bottom: 1px solid #eee;">${dni}</td></tr>
      <tr><td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Domicilio</strong></td><td style="padding: 8px; border-bottom: 1px solid #eee;">${address}</td></tr>
      <tr><td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Teléfono</strong></td><td style="padding: 8px; border-bottom: 1px solid #eee;">${phone}</td></tr>
      <tr><td style="padding: 8px; border-bottom: 1px solid #eee;"><strong>Email</strong></td><td style="padding: 8px; border-bottom: 1px solid #eee;">${email}</td></tr>
    </table>

    <p style="margin-bottom: 15px; line-height: 1.6;"><strong>Solicito:</strong></p>

    <ol style="margin-bottom: 20px; line-height: 1.8;">
      <li>Eliminación completa e inmediata de todos mis datos personales.</li>
      <li>Confirmación escrita de la eliminación dentro de los 10 días hábiles.</li>
      <li>Notificación a terceros que hayan recibido mis datos.</li>
      <li>Cesación de cualquier tratamiento futuro.</li>
    </ol>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      En caso de no recibir respuesta satisfactoria, me reservo el derecho de denunciar ante la <strong>Agencia de Acceso a la Información Pública</strong> y/o iniciar acciones legales.
    </p>

    <p style="margin-bottom: 40px; line-height: 1.6;">
      Sin otro particular, saludo atentamente.
    </p>

    <p style="margin-bottom: 5px;">
      <strong>${fullName}</strong><br />
      DNI: ${dni}<br />
      ${address}<br />
      ${phone} · ${email}
    </p>

    <p style="margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px;">
      Este documento fue generado por TraceLess - Herramienta de Protección de Privacidad<br />
      Fundamento legal: Ley 25.326 - Protección de Datos Personales (Argentina)
    </p>
  </div>`
}
