import type { Breach } from "@/data/breaches"

export const PROFILE_KEY = "traceless_profile"

export interface UserProfile {
  name: string
  address?: string
  dni?: string
}

export function generateDeletionLetter(query: string, breach: Breach, profile?: UserProfile): string {
  const date = new Date().toLocaleDateString("es-AR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const fullName = profile?.name || "[TU NOMBRE COMPLETO]"
  const addressLine = profile?.address || "[Dirección (opcional)]"
  const dniLine = profile?.dni || "[DNI/Pasaporte (opcional)]"

  return `Asunto: Data Deletion Request - Right to Erasure / Derecho al Olvido

${date}

To: Privacy Department / Data Protection Officer
${breach.name}
${breach.domain}

Dear Sir or Madam,

I am writing to request the complete deletion of my personal data associated with the email address ${query}, in accordance with the following regulations:

1. **GDPR (General Data Protection Regulation)** - Article 17: Right to Erasure
   (Applicable in the European Union and for companies operating in/with EU citizens)

2. **CCPA (California Consumer Privacy Act)** - Section 1798.105: Right to Delete
   (Applicable for California residents and companies doing business in California)

3. **Ley 25.326 - Protección de Datos Personales** (Argentina)
   (Applicable for Argentine citizens and companies processing Argentine data)

4. **Additional local data protection laws** as applicable in your jurisdiction.

**Context of this request:**

My personal data was exposed in a security breach at ${breach.name} on ${breach.date || "an unknown date"}. The compromised data includes: ${breach.compromisedData.join(", ")}.

**I hereby request:**

1. Complete deletion of all personal data associated with ${query} from your systems and databases.
2. Written confirmation that such deletion has been carried out.
3. Notification to any third parties who received my data about this deletion request.
4. Information about the timeframe for complete deletion (maximum 30 days as per GDPR).

This request is made in exercise of my fundamental right to data protection and privacy.

I expect a response within 30 days as required by applicable data protection regulations.

Sincerely,

${fullName}
Email: ${query}
${addressLine}
${dniLine}

---
This message was generated by TraceLess - Privacy Protection Tool`
}

export function generateDeletionLetterHTML(query: string, breach: Breach, date: string, profile?: UserProfile): string {
  const d = new Date(date)
  const dateStr = d.toLocaleDateString("es-AR", { day: "numeric", month: "long", year: "numeric" })
  const fullName = profile?.name || "[TU NOMBRE COMPLETO]"
  const addressLine = profile?.address ? `<br />${profile.address}` : ""
  const dniLine = profile?.dni ? `<br />${profile.dni}` : ""

  return `<div style="font-family: 'Georgia', serif; max-width: 700px; margin: 0 auto; padding: 60px 40px; color: #111;">
    <p style="text-align: right; color: #666; font-size: 14px; margin-bottom: 40px;">${dateStr}</p>

    <p style="margin-bottom: 30px;">
      <strong>${breach.name}</strong><br />
      Att: Privacy Department / Data Protection Officer<br />
      ${breach.domain}
    </p>

    <p style="margin-bottom: 20px;"><strong>Ref: Data Deletion Request - Right to Erasure</strong></p>

    <p style="margin-bottom: 15px;">Dear Sir or Madam,</p>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      I am writing to request the <strong>complete deletion</strong> of all my personal data
      associated with the email address <strong>${query}</strong>,
      in accordance with the following data protection regulations:
    </p>

    <ul style="margin-bottom: 20px; line-height: 1.8; padding-left: 20px;">
      <li><strong>GDPR</strong> (General Data Protection Regulation) - Article 17: Right to Erasure</li>
      <li><strong>CCPA</strong> (California Consumer Privacy Act) - Section 1798.105: Right to Delete</li>
      <li><strong>Ley 25.326</strong> - Protección de Datos Personales (Argentina)</li>
      <li>Any other applicable local data protection legislation</li>
    </ul>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      My personal data was exposed in a security breach at
      <strong>${breach.name}</strong> on <strong>${breach.date}</strong>.
      The compromised data includes: <strong>${breach.compromisedData.join(", ")}</strong>.
    </p>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      In accordance with the above regulations, I request that:
    </p>

    <ol style="margin-bottom: 20px; line-height: 1.8;">
      <li>All my personal data be deleted from your systems and databases.</li>
      <li>Any processing of my data be discontinued.</li>
      <li>Third parties who received my data be notified of this deletion request.</li>
      <li>Written confirmation of deletion be provided within 30 days.</li>
    </ol>

    <p style="margin-bottom: 15px; line-height: 1.6;">
      I expect a response within 30 days as required by applicable data protection regulations.
    </p>

    <p style="margin-bottom: 40px; line-height: 1.6;">
      I look forward to your prompt response.
    </p>

    <p style="margin-bottom: 5px;">Sincerely,</p>
    <p>
      <strong>${fullName}</strong><br />
      ${query}${addressLine}${dniLine}
    </p>

    <p style="margin-top: 40px; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px;">
      This message was generated by TraceLess - Privacy Protection Tool
    </p>
  </div>`
}

export function generateMasterDeletionLetter(emails: string[], profile?: UserProfile): string {
  const date = new Date().toLocaleDateString("es-AR", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const fullName = profile?.name || "[TU NOMBRE COMPLETO]"
  const contactEmail = emails[0] || "[Correo de contacto]"
  const addressLine = profile?.address ? `\n${profile.address}` : "\n[Dirección (opcional)]"

  const emailList = emails.map((e) => `  - ${e}`).join("\n")

  return `Asunto: Data Deletion Request - Right to Erasure / Derecho al Olvido

${date}

To: Privacy Department / Data Protection Officer

Dear Sir or Madam,

I am writing to request the complete deletion of my personal data associated with the following email addresses:

${emailList}

This request is made in accordance with:

1. **GDPR** (General Data Protection Regulation) - Article 17: Right to Erasure
2. **CCPA** (California Consumer Privacy Act) - Section 1798.105: Right to Delete
3. **Ley 25.326** - Protección de Datos Personales (Argentina)
4. Any other applicable local data protection legislation

I request:
1. Complete deletion of all my personal data from your systems.
2. Written confirmation of deletion within 30 days.
3. Notification to third parties who received my data about this request.

Sincerely,

${fullName}
Email: ${contactEmail}${addressLine}

---
This message was generated by TraceLess - Privacy Protection Tool`
}
